CREATE TABLE tblUsuarioWeb
(
UserId INT IDENTITY PRIMARY KEY,
NombreUsuario VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
[Password] VARCHAR(100) NOT NULL,
[FechaModificacion] DATETIME DEFAULT GETDATE(),
CONSTRAINT Email_User UNIQUE(Email)
)